name: Build on Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    env:
      GHC_VERSION: 8.10.1
      # Darcs 2.16.5 doesn't build on Windows, next release should do
      DARCS_VERSION: 2.18.2
    steps:
      - uses: actions/checkout@v2
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install archiver (to unpack xz files)
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: install -y archiver

      - name: Download ghc
        run: Invoke-WebRequest https://downloads.haskell.org/~ghc/$env:GHC_VERSION/ghc-$env:GHC_VERSION-x86_64-unknown-mingw32.tar.xz -OutFile ghc-$env:GHC_VERSION.tar.xz

      - name: Extract ghc
        run: arc unarchive ghc-$env:GHC_VERSION.tar.xz

      - name: Add ghc to PATH
        run: Get-Location | Join-Path -ChildPath ghc-$env:GHC_VERSION\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: ghc details
        run: |
          (Get-Command ghc).Source
          ghc --version

      - name: cabal details
        run: |
          (Get-Command cabal).Source

      - name: Download the darcs source tarball
        run: Invoke-WebRequest https://hackage.haskell.org/package/darcs-$Env:DARCS_VERSION/darcs-$Env:DARCS_VERSION.tar.gz -OutFile darcs-$Env:DARCS_VERSION.tar.gz

      - name: Extract darcs source
        run: tar -xvzf darcs-$Env:DARCS_VERSION.tar.gz

      - name: build darcs
        run: |
          cd darcs-$Env:DARCS_VERSION
          cabal v2-update
          cabal v2-build exe:darcs -f-curl -fstatic
          cp dist-newstyle/build/x86_64-windows/ghc-$env:GHC_VERSION/darcs-$Env:DARCS_VERSION/build/darcs/darcs.exe ../darcs.exe

      - uses: actions/upload-artifact@v2
        with:
          name: darcs.exe
          path: darcs.exe
