name: Build on Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    env:
      DARCS_VERSION: 2.18.3
    steps:
      - uses: actions/checkout@v4
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2.0.0

      - name: download older ghc
        run: Invoke-WebRequest https://downloads.haskell.org/~ghc/9.8.2/ghc-9.8.2-x86_64-unknown-mingw32.tar.xz -OutFile ghc-9.8.2-x86_64-unknown-mingw32.tar.xz

      - name: extract ghc
        timeout-minutes: 2
        run: |
          ls -lh
          tar -xzf ghc-9.8.2-x86_64-unknown-mingw32.tar.xz

      - name: ghc details
        run: |
          ls
          ghc-9.8.2-x86_64-unknown-mingw32\bin\ghc --version

      - name: cabal details
        run: |
          ghc-9.8.2-x86_64-unknown-mingw32\bin\cabal --version

      - name: Download the darcs source tarball
        run: Invoke-WebRequest https://hackage.haskell.org/package/darcs-$Env:DARCS_VERSION/darcs-$Env:DARCS_VERSION.tar.gz -OutFile darcs-$Env:DARCS_VERSION.tar.gz

      - name: Extract darcs source
        run: tar -xvzf darcs-$Env:DARCS_VERSION.tar.gz

      - name: build darcs
        run: |
          cd darcs-$Env:DARCS_VERSION
          ghc-9.8.2-x86_64-unknown-mingw32\bin\cabal v2-update
          mkdir ~\bin -ea 0
          ghc-9.8.2-x86_64-unknown-mingw32\bin\cabal v2-install exe:darcs --install-method=copy --installdir=$env:USERPROFILE\bin -f-curl -fstatic
          ~\bin\darcs --version
          cp ~\bin\darcs.exe ..\darcs.exe

      - uses: actions/upload-artifact@v4
        with:
          name: darcs.exe
          path: darcs.exe
