name: Build on Windows

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/windows.yml'

jobs:
  build:
    runs-on: windows-2019
    env:
      DARCS_VERSION: 2.18.3
    steps:
      - uses: actions/checkout@v4
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2.0.0
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8.2'
      - name: ghc details
        run: ghc --version
      - name: cabal details
        run: cabal --version

      - name: Download the darcs source tarball
        run: Invoke-WebRequest https://hackage.haskell.org/package/darcs-$Env:DARCS_VERSION/darcs-$Env:DARCS_VERSION.tar.gz -OutFile darcs-$Env:DARCS_VERSION.tar.gz

      - name: Extract darcs source
        run: tar -xvzf darcs-$Env:DARCS_VERSION.tar.gz

      - name: build darcs
        run: |
          cd darcs-$Env:DARCS_VERSION
          cabal v2-update
          mkdir ~\bin -ea 0
          cabal v2-install exe:darcs --install-method=copy --installdir=$env:USERPROFILE\bin -f-curl -fstatic
          ~\bin\darcs --version
          cp ~\bin\darcs.exe ..\darcs.exe

      - uses: actions/upload-artifact@v4
        with:
          name: darcs.exe
          path: darcs.exe
