name: Build on Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    env:
      DARCS_VERSION: 2.18.2
    steps:
      - uses: actions/checkout@v4
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2.0.0

      - name: ghc details
        run: |
          (Get-Command ghc).Source
          ghc --version

      - name: cabal details
        run: |
          (Get-Command cabal).Source

      - name: Download the darcs source tarball
        run: Invoke-WebRequest https://hackage.haskell.org/package/darcs-$Env:DARCS_VERSION/darcs-$Env:DARCS_VERSION.tar.gz -OutFile darcs-$Env:DARCS_VERSION.tar.gz

      - name: Extract darcs source
        run: tar -xvzf darcs-$Env:DARCS_VERSION.tar.gz

      - name: build darcs
        run: |
          cd darcs-$Env:DARCS_VERSION
          cabal v2-update
          mkdir ~\bin -ea 0
          cabal v2-install exe:darcs -f-curl -fstatic --install-method=copy --install-dir=~\bin
          cp ~\bin\darcs.exe ..\darcs.exe

      - uses: actions/upload-artifact@v4
        with:
          name: darcs.exe
          path: darcs.exe
